#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "syncserver-rs"
name = "Firefox SyncStorage"

description.en = "Synchronize tabs, passwords, history etc. between your Firefox instances"
description.fr = "Synchronisez for onglets, mot de passe, historique etc entre vos Firefox"

version = "0.22.1~ynh1"

maintainers = ["orhtej2"]

[upstream]
license = "MPL-2.0"
website = "https://www.mozilla.org/en-GB/firefox/features/sync/"
admindoc = "https://github.com/mozilla-services/syncstorage-rs/blob/master/docs/config.md"
code = "https://github.com/mozilla-services/syncstorage-rs"
fund = "https://donate.mozilla.org/en-GB/"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = ["amd64", "arm64", "armhf", "i386"]
multi_instance = true

sso = false
ldap = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

[resources]

    [resources.sources]
        [resources.sources.main]
        url = "https://github.com/mozilla-services/syncstorage-rs/archive/refs/tags/0.22.1.tar.gz"
        sha256 = "15af7706c9651fbb2c7b3418d73b215bdb6bbbdd05550263f2878e345fd02667"
        autoupdate.strategy = "latest_github_tag"
        autoupdate.needs_manual_tweaks = true

        [resources.sources.bookworm]
        amd64.url = "https://github.com/YunoHost-Apps/syncstorage-rs-build/releases/download/syncserver-0.22.1/syncserver-0.22.1-bookworm-x86_64-unknown-linux-gnu.zst"
        amd64.sha256 = "b35fe6f43da7d8307cf1be36bcf761c3cf1f9b2f42ec645e039d5a7a1b77ed79"
        autoupdate.asset.amd64 = "syncserver-\\d+(\\.\\d+)+-bookworm-x86_64-unknown-linux-gnu.zst"

        arm64.url = "https://github.com/YunoHost-Apps/syncstorage-rs-build/releases/download/syncserver-0.22.1/syncserver-0.22.1-bookworm-aarch64-unknown-linux-gnu.zst"
        arm64.sha256 = "008e5dc3f81b2f443dd17ffd29c233f254209e67d7baf363001b662ddd397728"
        autoupdate.asset.arm64 = "syncserver-\\d+(\\.\\d+)+-bookworm-aarch64-unknown-linux-gnu.zst"

        armhf.url = "https://github.com/YunoHost-Apps/syncstorage-rs-build/releases/download/syncserver-0.22.1/syncserver-0.22.1-bookworm-armv7-unknown-linux-gnueabihf.zst"
        armhf.sha256 = "bc8da9367effee88a0e648277d34a48197fdfb2f1077b483a17ab1f68c7ec4be"
        autoupdate.asset.armhf = "syncserver-\\d+(\\.\\d+)+-bookworm-armv7-unknown-linux-gnueabihf.zst"

        i386.url = "https://github.com/YunoHost-Apps/syncstorage-rs-build/releases/download/syncserver-0.22.1/syncserver-0.22.1-bookworm-i686-unknown-linux-gnu.zst"
        i386.sha256 = "1ed6126954fc26c18ed819a13e8c77ecc8288747a7b79e05a51690a27725dff8"
        autoupdate.asset.i386 = "syncserver-\\d+(\\.\\d+)+-bookworm-i686-unknown-linux-gnu.zst"

        autoupdate.strategy = "latest_github_release"
        autoupdate.upstream = "https://github.com/YunoHost-Apps/syncstorage-rs-build"
        autoupdate.needs_manual_tweaks = true
        autoupdate.version_regex = "syncserver-(\\d+\\.\\d+\\.\\d+\\.?\\d{0,})"
        rename = "syncserver"
        in_subdir = false
        prefetch = false

        [resources.sources.trixie]
        amd64.url = "https://github.com/YunoHost-Apps/syncstorage-rs-build/releases/download/syncserver-0.22.1/syncserver-0.22.1-trixie-x86_64-unknown-linux-gnu.zst"
        amd64.sha256 = "aafdb305d7d0638011e239d08665204d052fd2cb816da7fb3b1d2a51ea4510d1"
        autoupdate.asset.amd64 = "syncserver-\\d+(\\.\\d+)+-trixie-x86_64-unknown-linux-gnu.zst"

        arm64.url = "https://github.com/YunoHost-Apps/syncstorage-rs-build/releases/download/syncserver-0.22.1/syncserver-0.22.1-trixie-aarch64-unknown-linux-gnu.zst"
        arm64.sha256 = "9e793c76bf2d7c3ce59be3c25742325b219e6a5d850835c067b6301087403195"
        autoupdate.asset.arm64 = "syncserver-\\d+(\\.\\d+)+-trixie-aarch64-unknown-linux-gnu.zst"

        armhf.url = "https://github.com/YunoHost-Apps/syncstorage-rs-build/releases/download/syncserver-0.22.1/syncserver-0.22.1-trixie-armv7-unknown-linux-gnueabihf.zst"
        armhf.sha256 = "482286d57d7b8f00ef90629589bc406049923bfac83fda712f18a496892142b6"
        autoupdate.asset.armhf = "syncserver-\\d+(\\.\\d+)+-trixie-armv7-unknown-linux-gnueabihf.zst"

        autoupdate.strategy = "latest_github_release"
        autoupdate.upstream = "https://github.com/YunoHost-Apps/syncstorage-rs-build"
        autoupdate.needs_manual_tweaks = true
        autoupdate.version_regex = "syncserver-(\\d+\\.\\d+\\.\\d+\\.?\\d{0,})"
        rename = "syncserver"
        in_subdir = false
        prefetch = false

        [resources.sources.diesel]
        amd64.url = "https://github.com/YunoHost-Apps/syncstorage-rs-build/releases/download/diesel-v2.3.6/diesel-v2.3.6-bookworm-x86_64-unknown-linux-gnu.zst"
        amd64.sha256 = "9a1bbb1fd0dbbb9e4bb25b769434b7f42370a05077f6f1f850bff0a2dce5e2c2"
        autoupdate.asset.amd64 = "diesel-v\\d+(\\.\\d+)+-bookworm-x86_64-unknown-linux-gnu.zst"

        arm64.url = "https://github.com/YunoHost-Apps/syncstorage-rs-build/releases/download/diesel-v2.3.6/diesel-v2.3.6-bookworm-aarch64-unknown-linux-gnu.zst"
        arm64.sha256 = "1712699e7ffff1e69c2a24bb549416e5607b720b9ac8ea3ada887ac3656ca2ac"
        autoupdate.asset.arm64 = "diesel-v\\d+(\\.\\d+)+-bookworm-aarch64-unknown-linux-gnu.zst"

        armhf.url = "https://github.com/YunoHost-Apps/syncstorage-rs-build/releases/download/diesel-v2.3.6/diesel-v2.3.6-bookworm-armv7-unknown-linux-gnueabihf.zst"
        armhf.sha256 = "b284f973ad38afd150ddf9392abf53d3c5d0ac9a1a634b1fcf188dcc3272a0d9"
        autoupdate.asset.armhf = "diesel-v\\d+(\\.\\d+)+-bookworm-armv7-unknown-linux-gnueabihf.zst"

        i386.url = "https://github.com/YunoHost-Apps/syncstorage-rs-build/releases/download/diesel-v2.3.6/diesel-v2.3.6-bookworm-i686-unknown-linux-gnu.zst"
        i386.sha256 = "a1d4b59fdba4e4303a097c3b0f68ff165c3d806c2e075833fe2a8df24ce9c572"
        autoupdate.asset.i386 = "diesel-v\\d+(\\.\\d+)+-bookworm-i686-unknown-linux-gnu.zst"

        autoupdate.strategy = "latest_github_release"
        autoupdate.upstream = "https://github.com/YunoHost-Apps/syncstorage-rs-build"
        autoupdate.needs_manual_tweaks = true
        autoupdate.version_regex = "diesel-v(\\d+\\.\\d+\\.\\d+)"
        rename = "diesel"
        in_subdir = false


    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    main.show_tile = false
    main.allowed = "visitors"
    main.protected = true

    [resources.ports]

    [resources.apt]
    packages = [
      "mariadb-server",
      "libmariadb-dev-compat", 
      "python3-pip",
      "python3-setuptools",
      "python3-wheel",
      "build-essential",
      "libssl-dev",
      "libcurl4",
      "python3-venv",
      "pkg-config"
    ]

    [resources.database]
    type = "mysql"
