#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "syncserver-rs"
name = "Firefox SyncStorage"

description.en = "Synchronize tabs, passwords, history etc. between your Firefox instances"
description.fr = "Synchronisez for onglets, mot de passe, historique etc entre vos Firefox"

version = "0.21.1.1~ynh2"

maintainers = ["orhtej2"]

[upstream]
license = "MPL-2.0"
website = "https://www.mozilla.org/en-GB/firefox/features/sync/"
admindoc = "https://github.com/mozilla-services/syncstorage-rs/blob/master/docs/config.md"
code = "https://github.com/mozilla-services/syncstorage-rs"
fund = "https://donate.mozilla.org/en-GB/"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

sso = false
ldap = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

[resources]

    [resources.sources]
        [resources.sources.main]
        amd64.url = "https://github.com/orhtej2/syncstorage-rs-yunohost-builds/releases/download/0.21.1.1/syncserver-0.21.1.1-x86_64-unknown-linux-gnu.zst"
        amd64.sha256 = "3cfd5ca885a0bc93bcfb6517a3361392e0b214983e53bd6565cc78b01e715fa1"
        autoupdate.asset.amd64 = "syncserver-\\d+(\\.\\d+)+-x86_64-unknown-linux-gnu.zst"

        arm64.url = "https://github.com/orhtej2/syncstorage-rs-yunohost-builds/releases/download/0.21.1.1/syncserver-0.21.1.1-aarch64-unknown-linux-gnu.zst"
        arm64.sha256 = "5f19f760d765b05bd3fc400269abfc3e34aa9f4641cff62ec481e16821b18f77"
        autoupdate.asset.arm64 = "syncserver-\\d+(\\.\\d+)+-aarch64-unknown-linux-gnu.zst"

        armhf.url = "https://github.com/orhtej2/syncstorage-rs-yunohost-builds/releases/download/0.21.1.1/syncserver-0.21.1.1-armv7-unknown-linux-gnueabihf.zst"
        armhf.sha256 = "9b296c5497fcd9846d475d4c73c87e4022404562f93da9a100e4b45214a5bb2e"
        autoupdate.asset.armhf = "syncserver-\\d+(\\.\\d+)+-armv7-unknown-linux-gnueabihf.zst"

        i386.url = "https://github.com/orhtej2/syncstorage-rs-yunohost-builds/releases/download/0.21.1.1/syncserver-0.21.1.1-i686-unknown-linux-gnu.zst"
        i386.sha256 = "ae80a8e0aa1bdb312281475301b6ac8e091cccb5e1c00bf939b0fdfb00964878"
        autoupdate.asset.i386 = "syncserver-\\d+(\\.\\d+)+-i686-unknown-linux-gnu.zst"

        autoupdate.strategy = "latest_github_release"
        autoupdate.upstream = "https://github.com/orhtej2/syncstorage-rs-yunohost-builds"
        autoupdate.needs_manual_tweaks = true
        rename = "syncserver"
        in_subdir = false


        [resources.sources.diesel]
        amd64.url = "https://github.com/orhtej2/syncstorage-rs-yunohost-builds/releases/download/0.21.1.1/diesel_cli-v2.3.6-x86_64-unknown-linux-gnu.zst"
        amd64.sha256 = "d16352bf44fc7676dcd14d554f811deaa84184b782c11faf326b659bc631307c"
        autoupdate.asset.amd64 = "diesel_cli-v\\d+(\\.\\d+)+-x86_64-unknown-linux-gnu.zst"

        arm64.url = "https://github.com/orhtej2/syncstorage-rs-yunohost-builds/releases/download/0.21.1.1/diesel_cli-v2.3.6-aarch64-unknown-linux-gnu.zst"
        arm64.sha256 = "3ed28a95ef97336b26e75dff534ef9f58898c79f6603add37f40d7f3f93d045a"
        autoupdate.asset.arm64 = "diesel_cli-v\\d+(\\.\\d+)+-aarch64-unknown-linux-gnu.zst"

        armhf.url = "https://github.com/orhtej2/syncstorage-rs-yunohost-builds/releases/download/0.21.1.1/diesel_cli-v2.3.6-armv7-unknown-linux-gnueabihf.zst"
        armhf.sha256 = "5fe6b1c3e4e1441b39d1ea8f13c1efac69e5db380a6d949b5c8c39a870580f11"
        autoupdate.asset.armhf = "diesel_cli-v\\d+(\\.\\d+)+-armv7-unknown-linux-gnueabihf.zst"

        i386.url = "https://github.com/orhtej2/syncstorage-rs-yunohost-builds/releases/download/0.21.1.1/diesel_cli-v2.3.6-i686-unknown-linux-gnu.zst"
        i386.sha256 = "a540164f5f3acab06e70b340dfbc81008330df6523a6813a0ca8df2c522b95de"
        autoupdate.asset.i386 = "diesel_cli-v\\d+(\\.\\d+)+-i686-unknown-linux-gnu.zst"

        autoupdate.strategy = "latest_github_release"
        autoupdate.upstream = "https://github.com/orhtej2/syncstorage-rs-yunohost-builds"
        autoupdate.needs_manual_tweaks = true
        rename = "diesel"
        in_subdir = false


        [resources.sources.upstream]
        url = "https://github.com/mozilla-services/syncstorage-rs/archive/bf4ba77bdcd06b2e450b16076d55f7e1eaa6bf08.tar.gz"
        sha256 = "93034f05d684436ce33563f25e1513923983f0637268bccde6ffac9664a9e55b"
        autoupdate.strategy = "latest_github_tag"
        autoupdate.needs_manual_tweaks = true


    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    main.show_tile = false
    main.allowed = "visitors"
    main.protected = true

    [resources.ports]

    [resources.apt]
    packages = [
      "mariadb-server",
      "libmariadb-dev-compat", 
      "python3-pip",
      "python3-setuptools",
      "python3-wheel",
      "build-essential",
      "libssl-dev",
      "libcurl4",
      "python3-venv",
      "pkg-config"
    ]

    [resources.database]
    type = "mysql"
