#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]
    test_upgrade_from.84eb61dc.name = "Upgrade from 0.18.1~3"
    test_upgrade_from.7ef1f6f6.name = "Upgrade from 0.20.0~1"
    