#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]
    test_upgrade_from.fa15ef8eaade799cfe7959b876ec5ae3a57168e6.name = "Upgrade from 0.20.0~1"
    
