#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]
    test_upgrade_from.aa6de3354ef6bdfc7eefeec5be59a339ca80497e.name = "Upgrade from 0.20.0~1"
    
