#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]
    test_upgrade_from.08e07e598b5285570b6a90174340164c9235e3f4.name = "Upgrade from 0.20.0~1"
    test_upgrade_from.f1ce0e473860e1041f288c968daafbc1669d7ad4.name = "Upgrade from 0.23.3~2"
    
