#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

secret=$(ynh_string_random --length=40)
master_secret=$(ynh_string_random --length=40)
db_name_tokenserver="${db_name}_tokenserver"

ynh_app_setting_set --key=db_name_tokenserver --value=$db_name_tokenserver
ynh_app_setting_set --key=secret --value=$secret
ynh_app_setting_set --key=master_secret --value=$master_secret

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

ynh_hide_warnings ynh_exec_as_app RUSTUP_HOME="$install_dir"/.rustup CARGO_HOME="$install_dir"/.cargo bash -c 'curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -q -y'
export PATH="$install_dir/.cargo/bin:$PATH"
ynh_hide_warnings ynh_exec_as_app PATH=$PATH cargo install diesel_cli --no-default-features --features 'mysql'

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir/build"

#=================================================
# PROVISION SECOND DB
#=================================================

ynh_script_progression "Configuring second MySQL database..."
ynh_mysql_create_db "$db_name_tokenserver" "$db_user" "$db_pwd"

#=================================================
# BUILD
#=================================================

ynh_script_progression "Building the sources (it will take some time)..."

ynh_exec_as_app python -m venv "${install_dir}/venv"
(
	set +o nounset
	source "${install_dir}/venv/bin/activate"
	set -o nounset

	ynh_hide_warnings ynh_exec_as_app PATH=$PATH $install_dir/venv/bin/pip install --upgrade pip
	ynh_hide_warnings ynh_exec_as_app PATH=$PATH $install_dir/venv/bin/pip install --upgrade setuptools
    pushd $install_dir/build
        ynh_hide_warnings ynh_exec_as_app PATH=$PATH $install_dir/venv/bin/pip install -r requirements.txt
		ynh_hide_warnings ynh_exec_as_app PATH=$PATH $install_dir/venv/bin/pip install -r tools/tokenserver/requirements.txt
        ynh_hide_warnings ynh_exec_as_app PATH=$PATH cargo install --path ./syncserver --locked --root $install_dir  --no-default-features --features=syncstorage-db/mysql

		ynh_script_progression "Seeding the databases..."
		# syncstorage db
		diesel --database-url "mysql://$db_user:${db_pwd}@localhost/$db_name" migration --migration-dir syncstorage-mysql/migrations run

		# tokenserver db
		diesel --database-url "mysql://$db_user:${db_pwd}@localhost/$db_name_tokenserver" migration --migration-dir tokenserver-db/migrations run

		ynh_mysql_db_shell "$db_name_tokenserver" <<< "INSERT INTO services (id, service, pattern) VALUES (1, 'sync-1.5', '{node}/1.5/{uid}')";

		ynh_hide_warnings ynh_exec_as_app PATH=$PATH SYNC_TOKENSERVER__DATABASE_URL="mysql://$db_user:${db_pwd}@localhost/$db_name_tokenserver" $install_dir/venv/bin/python tools/tokenserver/add_node.py "https://${domain%%+(/)}" 10
    popd
)

ynh_safe_rm "$install_dir/.cargo"
ynh_safe_rm "$install_dir/.rustup"
ynh_safe_rm "$install_dir/.cache"
ynh_safe_rm "$install_dir/.local"
ynh_safe_rm "$install_dir/build"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

ynh_config_add_logrotate

yunohost service add $app --description="Firefox Sync Server (Rust)" --log="/var/log/$app/$app.log"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template="config.toml" --destination="$install_dir/config.toml"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start"  --wait_until="Server running on http://127.0.0.1"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
