#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEMD SERVICE
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

if ynh_hide_warnings yunohost service status $app >/dev/null; then
	yunohost service remove $app
fi

ynh_config_remove_systemd

ynh_config_remove_nginx

ynh_config_remove_logrotate

#=================================================
# DROP TOKENSERVER DB
#=================================================
ynh_script_progression "Deprovisioning TokenServer DB..."

ynh_mysql_drop_db "$db_name_tokenserver"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
