#!/bin/bash

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

#=================================================
# RESTORE THE MYSQL DATABASE
#=================================================
ynh_script_progression "Restoring the MySQL database..."

ynh_mysql_db_shell < ./db.sql

ynh_script_progression "Restoring tokenserver database..."
ynh_mysql_create_db "$db_name_tokenserver" "$db_user" "$db_pwd"
ynh_mysql_db_shell "$db_name_tokenserver" < ./db_tokenserver.sql

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
# RESTORE THE PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

# This should be a symetric version of what happens in the install script

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate

ynh_restore "/etc/systemd/system/$app.service"
systemctl enable $app.service --quiet

yunohost service add $app --description="Firefox Sync Server (Rust)" --log="/var/log/$app/$app.log"

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_systemctl --service=nginx --action=reload

# Typically you only have either $app or php-fpm but not both at the same time...
ynh_systemctl --service=$app --action="start"  --wait_until="Server running on http://127.0.0.1"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
